#include "icu.h"
#include "gpio.h"
#include "ultrasonic.h"
#include <util/delay.h>

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/
static volatile uint8 edgeNum=0;
static uint16 time=0;
/*
➢ Initialize the ICU driver as required.
➢ Setup the ICU call back function.
➢ Setup the direction for the trigger pin as output pin through the
GPIO driver*/
void Ultrasonic_init(void){

	Icu_ConfigType config={F_CPU_8,RISING};
	Icu_init(&config);

	Icu_setCallBack(Ultrasonic_edgeProcessing);

	GPIO_setupPinDirection(TRIGGER_PORT, TRIGGER_PIN, PIN_OUTPUT);

}

/*➢ Send the Trigger pulse to the ultrasonic*/
void Ultrasonic_Trigger(void){
	GPIO_writePin(TRIGGER_PORT, TRIGGER_PIN, 1);
	_delay_us(10);
	GPIO_writePin(TRIGGER_PORT, TRIGGER_PIN, 0);
}

/*
➢ Send the trigger pulse by using Ultrasonic_Trigger function.
➢ Start the measurements by the ICU from this moment.*/
uint16 Ultrasonic_readDistance(void){
	uint16 distance=0;

	Ultrasonic_Trigger();

	while(edgeNum!=2);/*waiting until Ultrasonic_edgeProcessing function finish*/

	edgeNum=0;

	/*sumarized equation for ==>Sound velocity = 340.00 m/s = 34000 cm/s The distance of Object (in cm) = 340000∗Time/2
	= 17000 * Time Now, here we have selected an internal 8MHz oscillator frequency for ATmega16, with
	Prescaler F_CPU/8 for timer frequency. Then time to execute 1 instruction is 1 us.
	So, the timer gets incremented after 1 us time elapse.
	= 17000 x (TIMER value) x 1 x 10^-6 cm
	= 0.017 x (TIMER value) cm
	= (TIMER value) / 58.8 cm   but time/57.5 more accurate*/
	distance=time/57.5;
	return distance;
}

/*
➢ This is the call back function called by the ICU driver.
➢ This is used to calculate the high time (pulse time) generated by
the ultrasonic sensor

==>When the rising edge capture occurs at the Echo pin which is connected to an
input of ATmega16, start Timer of ATmega16 and again wait for a falling edge on
the Echo pin.
==> As soon as the falling edge is captured at the Echo pin, the microcontroller reads
the count of the Timer*/

void Ultrasonic_edgeProcessing(void){
	edgeNum++;
	if(edgeNum==1){
		Icu_clearTimerValue();
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(edgeNum==2){
		time=Icu_getInputCaptureValue();
		Icu_setEdgeDetectionType(RISING);
	}
}

